# Generated by Django 3.0.4 on 2020-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200324_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processed'), ('F', 'Finished')], default='P', max_length=1),
        ),
    ]
