# Generated by Django 3.0.4 on 2020-03-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='parameters',
        ),
    ]
