# Generated by Django 3.0.4 on 2020-03-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('cart', '0003_remove_cartitem_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterWithResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50, null=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_results', to='cart.CartItem')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='parameters',
            field=models.ManyToManyField(null=True, related_name='parameter_orders', through='cart.ParameterWithResult', to='laboratory.Parameter'),
        ),
    ]
