# Generated by Django 3.0.4 on 2020-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_auto_20200324_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
